language: generic

branches:
  only:
    - master

os:
  - osx

matrix:
  include:
    - env: BUILD_OPTIONS=""
      osx_image: xcode10
    - env: BUILD_OPTIONS=""
    # - env: BUILD_OPTIONS="--build-from-source"
    # - env: BUILD_OPTIONS="--devel"
  fast_finish: true

before_install:
  - brew update

script:
  - travis_wait brew install Formula/kompose.rb $BUILD_OPTIONS
  - brew test Formula/kompose.rb
  - brew remove kompose
  - brew tap yuikns/kompose
  - brew install kompose
  - kompose version
  - ls -al /usr/local/bin